version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND1_URL: http://backend1:5000/rolldice
      BACKEND2_URL: http://backend2:5165/rolldice
  backend1:
    build: ./backend1
    ports:
      - "5000:5000"
  backend2:
    build: ./backend2
    ports:
      - "5165:5165"
